version: '3.6'

services:
 ollama:
    image: ollama/ollama:0.1.3
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11435:11434
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

 chatgpt:
    build: .
    ports:
      - 3000:3000
    environment:
      - 'DEFAULT_MODEL='
      - 'OLLAMA_HOST='
    depends_on:
      - ollama
    networks:
      - my_network

volumes:
 ollama:

networks:
 my_network:
    driver: bridge
