version: '1.0'

services:
 ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - chris_evil_llms
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3

 chatgpt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - 'DEFAULT_MODEL='
      - 'OLLAMA_HOST=http://ollama:11434'
    depends_on:
      - ollama
    networks:
      - chris_evil_llms

volumes:
 ollama:

networks:
 chris_evil_llms:
    driver: bridge
